packages:
  - packages/*
  - packages/shared/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
  - sharp
  - unrs-resolver
